language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
env:
  global:
    - POSTGRESQL_SERVICE_HOST=127.0.0.1
    - PG_USERNAME=postgres
    - PG_PASSWORD=
    - PG_DATABASE=travis_ci_test
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- "./travis-build.sh --quiet verify"
services:
- postgresql: "9.6"
deploy:
  - provider: azure_web_apps
    username: travis-deploy-user
    site: as-de-bat-api
    on:
      branch: master
  - provider: azure_web_apps
    username: travis-deploy-user
    site: as-te-bat-api
    on:
      branch: staging
