language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1
env:
  global:
  - secure: SWBz9hCvvAuDdyPtBLLw54t6XYzgs9ecjilNhjWRt/Az2L4d3xpZXIrxHtXkAFi1O+WRoYVcDfd6YO0eQHqI2FYlXO/w44SDhc/lFdVhsJpstpYaXk/bwQ7FuwwbWseAuRIhClemM5v8/UMcGdcy8YKeobv7Gf/brXPkCFN+2bA8oKacmS5g7XnLGnEbVfjXBzaQeHdd17k05+PNLKLg6vVbVNT8RVaGkDiBKS3hiwuXZzZ/z0aeuhg7Vw+u+e34GCoUWwCfftdDrmXRlnPjWuPRW+DDVEU8WmJFlbwzOnzswIPUfOCb9G5IjIt2+5oF4NMm4h0u74Jl8TpB1KQWgsd6zSxeBZrTVF2BqgbSEs3TSFY6cAoA6VB2Z9fb6Mqh+ukBVOpME+N+EjC5bI639xpIF4vz1/XiiLfsxRrzeidXkCnS5pT/nlOt3AShGp1J8eaKW+Ikf/11MiDneaa04JK2Pdp+RO4upjtXxnZY6sMrSlo4U3OegR5FxzCp9SAXgWv4zRyQVneZ1I9o30wphObfV5nGaFzaDkfmH78TC/f9jbclRR1J8raH+tfHwvQVBPjxgre6lw8mb2SSLaNnumsSxQyH3uO8Kv/s9EjnhZE0hF0f9luMGMpfVxgrtz2a7BHfADlyLxRZjA6oFDpEdS8lF03ml4gSgHRCmusaePs=
  - POSTGRESQL_SERVICE_HOST=127.0.0.1
  - PG_USERNAME=postgres
  - PG_PASSWORD=
  - PG_DATABASE=travis_ci_test
  - secure: medztQFAUUW8pBWDVl4na4/wMKaN2cT0TzPDO+BHRAd8BVTB705qVd9R1SqjTuvIVOKZqSJ37w2BCMRFQrbXsbR2gRsUNC+4pcs3GIfHMPAGk4Ck301HEsg7LKNeY9Nae+4GDjbRq2+7SDbbdjfpdkQOf9L9e1WL0pqeC2a/VCvgPBCHLBrAJhBhO/xZlLfvR7gZ6CZmpC64OPW1YmnDYCReE5ZbIDJ5x64uDUfZIkM1QYsAXgRva0Nk/OLLJdnlKyMPxw3i61wQK/nCBpd1w6/zonM9x/Wr1FOg/CrHYFxh1gwiEharryjgHkPcu7I7HYqcEN9WaMBk8BQGPZxagOoBuJYnqNILas48K6pZM6XdNSy1z3OniYTtSupagpd7FiH408k86Gvd8C+sr8m228IxQa0qgQ3wCC7gjMTtWG+dznEDvufBdyUAW+t6XbqF17Lnu0e61uKrrbn60tOYK3gqlGBSGoNZu7Jz3GOk291BlkNB/5gJ1mcTdFqecJ9Alu+cgAVtvpSAN4Yr5KAxUuyvYZwYllcdqezdL54mMp7UBdPhQnprQObATOoMIS+RaUaI6gb/XnqhasQQ09t7QMoNkbFD5ioLzhQGweoB5sp8XumR+OOdeLVE30rEUwbpeLH+1320bBaLPEgibwtTgjmJY0035jTxQJtumP0rlco=
  - secure: Dl4Z/UkwGnDr0E3VOhGC3Oxl+hWqM8OvZ/WYEQgVJPnEZw2nqi7VVCBvyk05V5TDL8tOUFs7XmvROsVgy3MArf5Ht+eTkr5QGj6JjyuD5sXZ/qT740ddAssqvy2qPR/aCCD+JZ+jwLdWBzI8CZSYNlQFrT4ymh9Z4E0YWZp4fG44xy522SUjhNiWfAf1i7J1imWtP6hlzv1x8o5tb9u2oThZRDppwyJ+q6c/h5nLUeprksF7Fa9gomM0ZF4J7lYIAkfh3OtCB7gNozU0JkbqTXeC6rrbeH9pbwrhxrwkHC/zMbzJJRP/o4+xjKOL4I856gjAjhOclyQrP7zJ4jtngl49+9co/erjAsNw3/MBSRgQ8LasMzi/kcFevgBv1V5BBK9iaXQsYbE0cw2r/I6oeX5jD6mUZXEFwRzgpbwImTPIsj6R9eHZ5RKyRTafmKDHiJfrBkkidYBD/5ylyHMLax19ztoTiwt2bvm6HuiAQ/PlhYwkO7pqgxH0i2Gglz5cW1hQ2UAdF+M8xnNCJQXOIYpgJ6p/L4MaO0v5uLSPuNp4NnkMCxG8dyMVhSV2PzjimpeAnTWs2y0T85tikFUS47EB8tWSTyB8QPFAi3Gs0lEY3GlJ6l22ZPmJSN8pbYGdUBdvC9MA3Sez6RSk2mX54ZattDFgYvUyIJ30+vcQYpY=
  - secure: RIlEYoYp0sS9xv5BTqUFbCIjMW7/hnzqKSpNb3P+RT1MK3ZTYeh+qwIEZKQuqbD4C+qZhQzVXcxeor1jk1TzmLHVipmNvOY6G2pdxGQqy6jJRmgOEqlOD0eqBBJ8y+ByeEdrcMlcskTPGU4xicVKlb3t9RVtgrtanUvZ7Frn6qCZoydIPt0znRMhuAHq+dYPke7Wv0HZopV7+7fTXugjdLdLQDhWbiE4sqPvCrFSQ5O3QZHKmZ8rMOduG8fhJwfvcGT+zlEwGy6Dgu0zku1iO40Dm9fJSL2gCp8kV/GbLoGijQj07mGAafJ6R7JnXFN4q+qGQNhf8Yr9dvKVlzUvaOv+UZ1ml7wdYeIBh/1HWvU9PeAAj8DLCS6A7CUS1ueLPOq2K8CZDRMKtNwM6BJVqyUXaHUSOPlsFWF7e7y+wU89DUkIUj9rYYFtITKIb4m5woI1WdHE97vY5hM+KrwRuRujdIDqyvwSRbOVewK5ZWk+FInz2YzjvWNwxj8dvfsdo+HaWxZy344lIuyzCY4lbHcNhHI6hPePMOee9VKLg6b8FrDtuyZV8emiGIIlz9FxDbBmdj/XmxmvmcJJIlXE2ul/TmGVoXvosXYxao88ee1fNfpw2uEG3rwuW/iOxTMk5yxp/fwpLEfMHLIoDP50y7/MIpuRbHXMxEHcuwh89Bo=
  # APP_CREDENTIALS_DEV_PWD
  - secure: qJ5wJDsNCCw9Ubn1uCLLu6QFnUe1bP330RVfgG+aWrCFsZQ/xnUrrrZIL8IRK+Jkb1fiheyur5nAXASjlS32654QldVqkXn8wzTsBvpqT0mB67VxGTzZyNrYui3oe4s3opzuAE/1mp/VxMz7GIpNBt3WWiJWBrBf2abwaR/sGnrpFnkXGEnwAzilfD9f2ii2eMZXoE85kXtH6RrcwWXAtb4ru7IM/UYd00SG/d0rfYEpiSlqTX+8pDCtYP6fJZVAefIiWo822c0B4FarZ5A2+27VBLE49YPU8ujOMxtAiDw92cVnd9zcdOPzd8FtcbEQ2ZSdr30oPF25y4sXi7BjAHiyWKJm7FU3qt6ce04PjKIyW7bd/QasPJIFsoFP3kylIjtQTb1WlESYgdj/01ymsVn0f16gbbRzyScV3f/pGY1GH+kiNs657wGSRwpQCZE2HlnXowVwawl+FgkXkJDgOJgikq+us5jDFGmfs3MaLF1De9S2h2pmkLn2cZqnQZFIkihbKEmTKOFVUU1EEmYedf12on7PhUAtzGAOAQjHzx3p1V6r91oxApOcCUjIOamCf8eVYRzPccda4WT7NxqaRMW9bB3aOllG2lacjF+55cEjhiKlM85fEnUDz2sVZjCLYcEQlhvr6vmxEmD2Exc2i4GZPrmeaSH3oblIv1R7Jo4=
  # APP_CREDENTIALS_STAGING_PWD
  - secure: dLUwDtdf4e/vDGV8GyVSdk82lDI+kcp6l80sNnlCvsifkOpYkeljy9Gv4rIESNsDC86V01LOwlGM8UwYhE3jYIxrHhfuX9g9Rit8dmW/zDJtf3Obsg0KmG3PkzvdKuHWpoBgOrnYNozQ+ZUe2SvG3XTVv0+MlL4BmZYnUAzMWDMYsXcLryT4zfb6d+JWSabTmcjC2/My5caBVJTdF5DfJCfhPzGKyO2zasB0A8pQAZlcuM8hzRzlbm9BMTuS146MczjZhyHStHTcewcHxdq3R8/sEN6NglZEabyO068erEjhfEe2RiQQ2fUBg3X3kIVwuOy9DZ/JIfxCh/NejpBQYrfQE0SP5ernseT6oZSidpFkc4kQpmgmFB59h67SDYnXJwzObTgnBae9f7yxHDZX1QCuxg3piXLOBjx1RJ/jgh1htEo4WvbCBzXvNONdxJp+KDaRovnGNTffTh/ypIhZfkRJRytqqjHhUE5L6yf99xggIqwjiYzksD+KRUWMRRFDDb7k7IO/Hsg5wV2569eTAOesbWI+yG7fY/r3FvSaH/YiQn204f1mcfsoRxw8jOKg0qrn0YUhRphPqqde111W0aFhFvKTMOV8wvkaMB1e9kNV5YIClPFMLHJW1fwke7tvozOMgaYaN+ea/pAlN86I1+CMwjpFLxYN489pCKM9qVA=
  # APP_CREDENTIALS_PROD_PWD
  - secure: V4PgSc2/2M+MUMlAhqGszr7N81kkme+XFtbZLgmFeBgz+o/HJcXmwW/j9vxxlpLDwvlKXd7/J09Ma1ZY13ZlX/Mqt+Rm+B/MUywu1GgmRu5hcNUJxebuBhLXSiKXvw9N84Ekw2XVsHEzZoV+H2H0HEnMDv8RuqjYtysk2gId0IFS8gY3TOWSFDvEbeBo2OCZdnrQbuiEzAAYu2SYeb9dKOn/ntAOQobipdD1Di343PFG2wTGNrLdbq2mYnygjEIKHpVeyjZ713Xhsesisjsiw5XYbogXZa9z+UBOgdYJ47eE3Yw1itjUOOBTkTowWgoPpCZFE3BQ9gZotYkRON/L+AXGLQZd7YdLGXJOwbaFC52TgNPKs3lUGqPeAA5VqXT/mtr0q2xirWDloP5W0RURs6aunlG18D7ADUfcmvZFI2a+RzCsvuAXqxRXwb0f3MW9i3toVzZk73cySSo+AB4nYFVo9W6vvY5e+LN6zGzXfTJ5heyR4grQzlx45zY64wIYvouN1DbrlKETjtHYJx0klBqJlu0+GGhSeudp+CBfeCALcKSTs5EpI1tkaYWk7B+aBxIWW3R4FxinjVZQEJzXuR/X0V8vjE/omX3hfDHXXGaMdcJuUaOqxjIJ2lraE01RuZQyqz2PBvSQpJOMpPOAPuL3YyHEvfQgsnbpcDE6pwE=
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- "./travis-build.sh --quiet verify"
services:
- postgresql: '9.6'
deploy:
- provider: script
  script: "./deploy.sh dev"
  on: master
- provider: script
  script: "./deploy.sh staging"
  on: staging
- provider: script
  script: "./deploy.sh prod"
  on: production
- provider: script
  script: "./travis-deploy-geocoder.sh $bat-dev-search-and-compare-api-app:$APP_CREDENTIALS_DEV_PWD
    bat-dev-search-and-compare-api-app"
  on: master
- provider: script
  script: "./travis-deploy-geocoder.sh $bat-staging-search-and-compare-api-app:$APP_CREDENTIALS_STAGING_PWD
    bat-staging-search-and-compare-api-app"
  on: staging
- provider: script
  script: "./travis-deploy-geocoder.sh $bat-prod-search-and-compare-api-app:$APP_CREDENTIALS_PROD_PWD
    bat-prod-search-and-compare-api-app"
  on: production
- provider: script
  skip_cleanup: true
  script: chmod +x ./travis-nuget-deploy.sh && ./travis-nuget-deploy.sh $NUGET_API_KEY
    $NUGET_SOURCE
  on:
    all_branches: true
notifications:
  slack:
    secure: LV9uQYUL169TE5cC5TpdbWqnSrz9SU4eMUTe1aRrLD3V0F3iSOFe+tW1wzjBiqGnZLzSnEpa2jZDnBdDUVf7XDFsE2goivoYp0RAfR+PHrzU9Ov2GTgyf7zztF7lJ3gUkiKQSr/PWg4tVIsc6tJb7sXEMkpdXklw4USmcR6pwMSEh8C/Lf1/prRD0kTnWjMoH9ZieSi3r32QY5SKaOS9CN8sVC1bCe1mQE/oAKHuc3BgE4TaD9rZ5VENkuP8mR4RhHtPhB9AfTWlSVDezfq+luHdIy6xjs/QxizzjyK0nwkbEw18BP3n0rgO/FRa2B/w8zkOHDuLXqPD5NmgZg8AMTRwJsyCUE7lrI9xlj5PpjpIAOk7oIDNgn1MgxjAwfX7Ht6IHOUn2vpA7QyPUNZueFm194myq2qmAYGdgwPnx0lslQ2YaymzP5nUh82F1TbfEaw3cXZ2wXa7VXK2NxXccvTrhA/niHVZ7YAh3QlvJsj/9DrBGxMrtRLvdx4fdqt7AAvR9fYcWjzwcjGM9bH3Vz5frxOX9E+mpt9Y2k4EodcZ3MrfYTDTfxBygi1pI+DNirMQ02orLLS6P6rFXfyMcraAo1c1NyzvpROXuFejSm1oJKVljsFuDzReFpjS7fch8rBwfqdTFrOM7HMhC+eT3Bzun5kTOI2i9jJ1j+ReBKo=
  on_success: always
  on_failure: always
