version: "3.2"
volumes:
  dbdata:
services:
  db:
    image: postgres:9.6-alpine
    # To preserve data between runs of docker-compose, we mount a folder from the host machine.
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" # outside:inside
  web:
    build: .
    ports:
      - "5001:80" # outside:inside
    depends_on:
      - db
    environment:
      - DatabaseConnection__Server=db
